### PR TITLE
SimpleStack Fixes migration

### PR DESCRIPTION
**Pull request by vdaron**
Here are the quick fixes present in SimpleStack

### CODE REVIEW

**Comment by vdaron** [comment]
@mirthy Some feedback ?

**Comment by mirthy** [comment]
Sorry!  I'll take a look now!

**Comment by vdaron** [comment]
Tks

**Comment by mirthy** [comment]
Pushed up to NuGet as 1.0.11

**Comment by rykerwilliams** [comment]
@vdaron Are you fixes contributed back to v3? I saw the other day that Mythz was accepting fixes on ServiceStack.Text v3, so I wonder if it makes sense to contribute them back? I'm looking at the best way to merge the changes there currently into our fork.

@mirthy Want to add me to the NServiceKit team? Maybe @vdaron  too? Looks like you have been active in the last month, but in the interest of moving the project further I'd like to join! Maybe you already have discussed how we can contribute fixes and reasonable things back to v3? Or how we merge their changes to NServiceKit? Only having 1 guy in the team vs https://github.com/orgs/ServiceStack/people is a bad look I think, for another wise great initiative.

**Comment by vdaron** [comment]
@rykerwilliams I didn't push my commits to ServiceStack V3 because it looked like a dead branch.
Merged pull requests of ServiceStack.Textv3 could certainly be integrated into NServiceKit.Text. 

Could you maybe contact their authors for approval ? 

I'm already a commiter for NServicekit, do not hesitate to send pull requests ! Any effort is always appreciated.

NServicekit is a fork of the ServiceStackv3 branch to ensure project continuity under BSD licence.

**Comment by rykerwilliams** [comment]
@vdaron I will be sure to contact those committers on the v3 branch and let them know about the initiative here. I wanted to have the contributors here give thoughts on if / when to submit patches back to v3 and the process for merging the v3 changes to NServiceKit. 

On pull requests: I have a few open now against the NServiceKit projects, mostly updates to the Travis CI build scripts and support for Mono, I'd love for you to have a look at them.

**Pull request merged**
